import type { Metadata } from "next";
import { Montserrat, Oxanium, JetBrains_Mono } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";

const montserratHeading = Montserrat({
  subsets: ["latin"],
  variable: "--font-heading",
});

const oxanium = Oxanium({ subsets: ["latin"], variable: "--font-sans" });

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        montserratHeading.variable,
        oxanium.variable,
        jetbrainsMono.variable,
        "h-full",
        "font-sans",
        "antialiased"
      )}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
